### ISSUE TITLE
DSC-TX5

### ISSUE THREAD

**Issue by elegiamexico** [ma1co/Sony-PMCA-RE#243]
I want to try to change the locked Japanese language in my DSC-TX5 
Then, with my DSC-TX5 connected, I tried:

pmca-console guess_firmware -f 0x51020000.zip

and I´ve got:

success: found matching file: gen3_0x51020000_0.dat

Then possibly the method works for DSC-TX5

Could you please let me know what can I further try?

Thanks and Best Regards

**Comment by ma1co** [comment]
Can you try with this file? [0x10210100.zip](https://github.com/ma1co/Sony-PMCA-RE/files/4187939/0x10210100.zip)

**Comment by elegiamexico** [comment]
Thank zou so much for your kind reply. 

I´ve got the following:
pmca-console guess_firmware -f 0x10210100.zip
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices
Querying mass storage device
Sony DSC is a camera in mass storage mode
Getting device info
Model name: DSC-TX5
Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen0_0x10210107_0.dat

Can then it be supported in updater shell?

**Comment by ma1co** [comment]
Thank you, the DSC-TX5 is now supported in updatershell. However, there are currently no tweaks available, because this is a pretty old camera.

I would still be interested in a firmware dump. Here's how to do that:

* Download the newest [build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts) of pmca-console.
* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by elegiamexico** [comment]
Done! (after several attempts).
Pity that there are no tweaks for my little camera. I have learnt that in many instances sony uses hardware locks which make impossible any changes in their devices.
Thanks all the same.

**Comment by VinBones** [comment]
This is heartbreaking i bought 8 of these in bulk and they're all japanese... if anyone can come up with a solution i'd be happy to pay a reward gamereded@gmail.com

**Comment by dreambold** [comment]
> gamereded@gmail.com

I can help you with the tweaks, do you have a laptop, by the way?

**Comment by dreambold** [comment]
> This is heartbreaking i bought 8 of these in bulk and they're all japanese... if anyone can come up with a solution i'd be happy to pay a reward [gamereded@gmail.com](mailto:gamereded@gmail.com)

I can help you with the tweaks, do you have a laptop, by the way? @VinBones

**Comment by VinBones** [comment]
Laptop & computer, so you understand how to tweak older models? Got
anywhere where I can contact as email is slow

**Comment by VinBones** [comment]
> > This is heartbreaking i bought 8 of these in bulk and they're all japanese... if anyone can come up with a solution i'd be happy to pay a reward [gamereded@gmail.com](mailto:gamereded@gmail.com)
> 
> I can help you with the tweaks, do you have a laptop, by the way? @VinBones

Yessir can you help me out?... waiting for your response 🙏

**Comment by dreambold** [comment]
@VinBones I sent you an email.
