### ISSUE TITLE
Sony unlocks new menu requires extracting files CXD90057.dat

### ISSUE THREAD

**Issue by Camerasupport** [ma1co/Sony-PMCA-RE#300]
CXD90057.dat is an indispensable file to unlock the new menu of A7SIII A1 FX3 A7M4.  This is an indispensable first step, which you can extract from the upgrade firmware on Sony's official website.  When you get CXD90057.dat it means you are 50% successful.  Good luck!

**Comment by nicustraton** [comment]
I can solve Sony, Nikon, Canon cameras firmware problems/issues after firmware update etc.

If you want to unlock region for your Sony FX3/FX30 camera or other model, in order to have latest firmware and PAL-NTSC, write me on whatsap +40727005523, country code Romania (+40) and number 727005523 or mail me: nicustraton.baron at gmail dot com.

You just have download a USB remote software, enter my IP, connect the camera with USB cable in Image Transfer (MSC) mode to a windows PC/laptop with Windows OS and Intel CPU and share the connection. I will unlock camera first and you pay after.

PS: if you have an older firmware version on camera and you know you have your camera from grey market If you want to update firmware to latest version, if you will update, you will lose PAL/NTSC so I recommend to let me unlock region first, update firmware to latest version and then unlock region again.

* this is a safest way becauseI will backup your camera original settings and firmware before any procedures.
