### ISSUE TITLE
Support for DSC-HX100V

### ISSUE THREAD

**Issue by bactac** [ma1co/Sony-PMCA-RE#314]
DSC-HX100V is not supported yet, is there anything I can do to help? It seems to work similarly to the DSC-HX200V which is already supported...

```
>pmca-console-v0.18-8-g01a6df3-win.exe updatershell
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX100V is a camera in MTP mode

Getting device info
Using firmware for model DSC-HX100V

Unknown device: DSC-HX100V
```

I've tried the `guess_firmware` procedures with [0x21020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3199140/0x21020000.zip),  [0x31020000.zip](https://github.com/ma1co/OpenMemories-Tweak/files/2624485/0x31020000.zip),   [0x41010000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3199140/0x21020000.zip) ,   [0x51030000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/6974551/0x51030000.zip),   [0x61020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3277480/0x61020000.zip), but got no matches.

```
>pmca-console-v0.18-8-g01a6df3-win.exe guess_firmware -f 0x21020000.zip
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX100V is a camera in MTP mode

Getting device info
Model name: DSC-HX100V

Trying 100 firmware images
Fail: No matching file found
```

Is there anything I can dump and upload to help add support to this camera?

**Comment by bactac** [comment]
I managed to use [fwtool.py](https://github.com/ma1co/fwtool.py) to enter service shell. I had forgotten to set the camera's USB mode to auto (didn't work on MTP).

After entering service shell, I dumped the bootrom and Backup.bin (let me know if uploading them would be useful). From this shell I could use `bk w 0x01070330 00` which was used on #313 and got clean HDMI on the DSC-HX100V! 

Thank you very much, this tool is amazing

**Comment by ma1co** [comment]
I would be interested in a firmware dump. Can you run `pull /dev/nflasha` in serviceshell and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx)?

In case this does not work, this should be the right file for `guess_firmware`: [0x11020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3322746/0x11020000.zip)

**Comment by bactac** [comment]
Thanks, that worked:
```
>pmca-console-v0.18-8-g01a6df3-win.exe guess_firmware -f 0x11020000.zip
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Model name: DSC-HX100V

Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen2_0x11020072_0.dat
```

As for `pull /dev/nflasha` it is writing an empty file:

```
>pmca-console-v0.18-8-g01a6df3-win.exe serviceshell
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to service mode

Waiting for camera to switch...
Found a camera in service mode
Authenticating
Starting service shell...

Welcome to platform shell.
Type `help` for the list of supported commands.
Type `exit` to quit.
>pull /dev/nflasha
Writing to .\nflasha...
>
```
I did pull nflasha on my DSC-HX200V and it took some time while printing the progress percentages, but for the DSC-HX100V it instantly created an empty file. Maybe there's an alternative file I should look for?

**Comment by ma1co** [comment]
Thanks, the DSC-HX100V should now be supported in updatershell. Can you try downloading the latest development build and then running `pull /dev/nflasha` and `bootloader` in updatershell? (Pulling /dev/nflasha in serviceshell seems to be broken on some older cameras...)

**Comment by bactac** [comment]
Thanks, worked flawlessly. I uploaded a `DSC-HX100V.zip` containing `nflasha`, `bootrom`, `boot1` and `Backup.bin`.

**Comment by SonicOrochi** [comment]
> After using Zadig to install libusb, I managed to start the camera in service shell mode. I had forgotten to set the camera's USB mode to auto (didn't work on MTP).
> 
> After entering service shell, I dumped the bootrom and Backup.bin using [fwtool.py](https://github.com/ma1co/fwtool.py) (let me know if uploading them would be useful). From this shell I could use `bk w 0x01070330 00` which was used on #313 and got clean HDMI on the DSC-HX100V!
> 
> Thank you very much, this tool is amazing

Hello, I've tried following these steps and managed to enter serviceshell and then if I try the `bk w 0x01070330 00` command, it says `Error: Unknown command`. Then, if I try the `shell` command and then, once again, `bk w 0x01070330 00` in the new shell line, it just replicates what I entered and nothing else happens.

Any help would be appreciated. Thanks.

EDIT: after scouring the deeps of the web I found this page https://kleo.hak.dog/sony-dsc-hx100v-clean-hdmi-capture which helped me figure that the version I was using, albeit being the latest, wasn't gonna cut it. So I installed all sorts of python modules to make the pmca-console.py work and then I finally managed to get the `help` info with many more commands to use.

**Comment by Johnn3101** [comment]
Hello, I come here because I need help, I can't use the updatershell command, it tells me this:
C:\Users\aurel>C:\Users\aurel\Desktop\pmca-console-v0.18-win.exe updatershell
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Using firmware for model DSC-HX100V

Unknown device: DSC-HX100V

C:\Users\aurel>

I honestly don't know what to do anymore.

**Comment by SonicOrochi** [comment]
> Hello, I come here because I need help, I can't use the updatershell command, it tells me this: C:\Users\aurel>C:\Users\aurel\Desktop\pmca-console-v0.18-win.exe updatershell Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific Looking for Sony devices
> 
> Querying mass storage device Sony DSC is a camera in mass storage mode
> 
> Getting device info Using firmware for model DSC-HX100V
> 
> Unknown device: DSC-HX100V
> 
> C:\Users\aurel>
> 
> I honestly don't know what to do anymore.

You'll probably have to install Python and use the script directly instead of the executable. Here's how I got it working on Windows (from memory - I had to redo this recently, a few hours ago, because for some ungodly reason my camera decided to reset to factory settings):

### Steps

1. **Install Python 3** and all dependencies from `requirements.txt`

2. **Run the service shell command:**
   ```bash
   python3 pmca-console.py serviceshell
   ```
   
   **If it doesn't work:**
   - Put your camera in **Mass Storage Mode** (check USB settings on camera)
   - Open **Zadig** → Options → List All Devices
   - Find your Sony device and install drivers for `libusb-win32`, `libusbK`, or `WinUSB`
   - **Keep trying different drivers** until the command works in PowerShell

3. **Once in service shell, test the commands:**
   ```bash
   help   # Shows available commands
   info   # Shows camera information
   ```
   
   **If `info` gives an error:**
   - Go back to Zadig and check the device list for the new mode (usually shows as "Sony USB Device")
   - Change/reinstall the driver for this device

4. **To remove the display overlay:**
   ```bash
   bk r 0x01070330   # Should return 01 (active)
   bk w 0x01070330 00   # Should return Success
   bk s   # Save changes
   exit    # Exit the program
   ```

**Note:** You'll likely need to switch drivers in Zadig multiple times as the camera changes modes. Just keep testing until each mode works!

This was formatted using AI because I have no idea how to make adequate posts here on github, but the information is from my experience.
