### ISSUE TITLE
Can anybody please share a copy that works for A7C?

### ISSUE THREAD

**Issue by peter-gz** [ma1co/Sony-PMCA-RE#388]
I want to unlock language options for my A7C. 
However, the built artifacts in [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts) are already removed. The latest built version mentioned was 18.xx.

Appreciate if someone could send me a copy (mylist1@gmail________.com).

**Comment by assafna** [comment]
https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip

**Comment by Yusaku974** [comment]
Just wanted to say, I was able to unlock all languages on my a7c (ILCE-7C)using this version of pmca-re, it allowed me to have the Service Mode button in the Tweak tab. It took me a while to get the driver to be effectively used (I didn't close Zadig and you should see Reinstall driver instead of Replace driver), otherwise you will get the libwinusb error message. The camera needs to be set on Mass Storage mode (so not Auto or MTP). 
Once you run the console version, then the GUI version, the camera info button should give you a message stating the camera is in Mass Storage mode. 
Once you press, the Service Mode button in the Tweak tab, the camera will come out of its usual Mass Storage splash screen and PMCA will show you another window with the tweaks.

 Thank you so very much, although I can read Katakana, I'm just much faster reading in English and time is of the essence when taking pictures sometimes.

**Comment by rkremeier** [comment]
> https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip

You wouldn't still happen to have this file would you?

If you could repost it, I would greatly appreciate it!

**Comment by Yusaku974** [comment]
> > https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip
> 
> You wouldn't still happen to have this file would you?
> 
> If you could repost it, I would greatly appreciate it!

I happen to have kept a copy of it. Not sure I'm allowed to attach it here, so here is a [link](https://www.swisstransfer.com/d/abd58ef1-6e8a-4287-adfa-4dfff455739a):
Hope this helps.

**Comment by rkremeier** [comment]
> > > https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip
> > 
> > 
> > You wouldn't still happen to have this file would you?
> > If you could repost it, I would greatly appreciate it!
> 
> I happen to have kept a copy of it. Not sure I'm allowed to attach it here, so here is a [link](https://www.swisstransfer.com/d/abd58ef1-6e8a-4287-adfa-4dfff455739a): Hope this helps.

Incredible! Thank you so much!

**Comment by peter-gz** [comment]
i have got the file. thanks for everyone that sent it to me.

**Comment by NarZhang** [comment]
How did you solve it in the end? Can you share the tutorial? My A6400 and A6100 have the same problem. If you can help me, thank you very much! zhangguge0323@gmail.com

**Comment by Yusaku974** [comment]
I was able to unlock all languages on my a7c (ILCE-7C)using this version of pmca-re, it allowed me to have the Service Mode button in the Tweak tab. It took me a while to get the driver to be effectively used (I didn't close Zadig and you should see Reinstall driver instead of Replace driver), otherwise you will get the libwinusb error message. The camera needs to be set on Mass Storage mode (so not Auto or MTP).
Once you run the console version, then the GUI version, the camera info button should give you a message stating the camera is in Mass Storage mode.
Once you press, the Service Mode button in the Tweak tab, the camera will come out of its usual Mass Storage splash screen and PMCA will show you another window with the tweaks.

Here is a new [link](https://www.swisstransfer.com/d/14102206-aecf-4d08-a167-40c60c3f9dc1) to PMCA. Hope it helps, there might a lot of videos showing how to do this online...

**Comment by vityspow** [comment]
Can anyone send me this file?? I have tried with several versions and it was imposible to unlock languages in my A7c.
Thanks in advance

**Comment by Yusaku974** [comment]
> Can anyone send me this file?? I have tried with several versions and it was imposible to unlock languages in my A7c. Thanks in advance

Here is a new **[link](https://www.swisstransfer.com/d/f89572d5-de87-4f48-b3a9-bfd794980b24)** to PMCA. Hope this helps.

**Comment by rkremeier** [comment]
Here's a link that shouldn't expire. https://www.mediafire.com/file/xoaor3qi8lhe03t/pmca-v0.18-18-gd634e6c-win.zip/file

**Comment by vityspow** [comment]
> > Can anyone send me this file?? I have tried with several versions and it was imposible to unlock languages in my A7c. Thanks in advance
> 
> Here is a new **[link](https://www.swisstransfer.com/d/f89572d5-de87-4f48-b3a9-bfd794980b24)** to PMCA. Hope this helps.

Thanks but it doesn't work either.

I have tried 18.0 no tweaks 18.18 everything ok but no tweak for languages and 18.22 the same.

So I am going to forget about it. Now I have 7 languages english, russian, indonesian, chinese... but not spanish..
