### ISSUE TITLE
Represent OpenMemories at EI conference?

### ISSUE THREAD

**Issue by aggregate** [ma1co/Sony-PMCA-RE#43]
I am one of the Program Committee members for the Photography, Mobile, and Immersive Imaging portion of the IS&T Electronic Imaging 2018 conference, to be held Jan. 28 - Feb 1, 2018 in Burlingame, CA, USA:

http://www.imaging.org/site/IST/IST/Conferences/EI/EI_2018/Conference/C_PMII.aspx

I have permission to organize a session on open source support for using commodity cameras in electronic imaging research. Ideally, I'd like to have people from several of the most significant projects participate in a panel session. This would involve each panelist giving a short overview of the project they are representing, followed by a discussion with questions from the audience.

Is there a developer who would be interested in attending and representing the OpenMemories project?

Thanks.

Hank Dietz, Professor & James F. Hardymon Chair in Networking
University of Kentucky, Electrical & Computer Engineering Dept.
329 Rose Street, Lexington, KY 40506-0633
http://aggregate.org/hankd/

**Comment by ma1co** [comment]
Hi, and sorry for the ultra late answer. I'm the main developer of OpenMemories. But as you can see from me not being very responsive on here, I don't really see me as a community "leader" or anything. OpenMemories is just a little side project where I publish my code online. The idea is to see what people do with it. But I'm not in a position to give a lot of support or be a real project leader. So I don't think I should be talking publically about it... But thanks for the invitation in any case, I hope your event turns out well!
