### ISSUE TITLE
Switch to MtpAppInstaller from MSC

### ISSUE THREAD

**Issue by erik-smit** [ma1co/Sony-PMCA-RE#5]
PMCADownloaderLib.dll switches devices from MSC (Mass-Storage) to MtpAppInstaller with a SCSI Vendor-specific CDB.

I need to use this for my ILCE-QX1 because it doesn't have a user-interface to allow switching USB mode.

For an example: https://github.com/erik-smit/sony-camera-usb/blob/master/SwitchMode.sh

P.S.: amazing piece of work you've done here. Wow. Just wow. Thanks.

**Comment by erik-smit** [comment]
Awesome, dude.

I can confirm it's working for me.

**Comment by ma1co** [comment]
Thanks for your help, I'm glad it works. This is great news btw, I didnt expect the QX1/QX30 to run android. This adds 2 new cameras to the devices "unofficially" running apps (the action cams since the AZ1 do as well).

Since there are no firmware upgrades available for the QX1, would you be interested in dumping the firmware?

**Comment by erik-smit** [comment]
Yes, I would be very interested in dumping the firmware.

Any clue how to do so?

**Comment by ma1co** [comment]
I have some ideas :D I've sent you an email last week.

**Comment by troop** [comment]
Any success with a rom dump from qx1?

**Comment by Deph0** [comment]
Sorry for necromancing- 
1) is it still possible to switch to SCSI or in any other way make QX1 available to install apps? (if it matters, using MacOSX10.10)
2) is a rom dump from qx1 still of interest?

thanks.
